version: "3"

services:
  bank-api:
    container_name: bank-api
    build: .
    environment:
      RUNTIME_ENV: 'test'
    volumes:
      - './bank:/app'
    ports:
      - "8080:8000"
    depends_on:
      - bank-db
  bank-db:
    container_name: bank-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mozilla
      POSTGRES_DB: Bank
    volumes:
      - './database_configs:/docker-entrypoint-initdb.d'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5